### ISSUE TITLE
Deploy stock values

### ISSUE THREAD

**Issue by mattbrailsford** [vendrhub/vendr-deploy#1]
As stock is held in a custom DB table, we need to review what we need to do to deploy stock values. 

Also, need to be careful here as we also don't want to deploy stock values post launch and accidentally reset them so it needs concideration.

**Comment by robertjf** [comment]
Hey @mattbrailsford did you end up getting this resolved?  Do you have any pointers on this for package developers with content/configuration in databases that needs to be deployed between environments?

**Comment by mattbrailsford** [comment]
I decided not to sync stock in the end due to it being so volatile. It just wouldn't make sense to deploy.
