### ISSUE TITLE
Dependency error when installing

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-deploy#13]
When installing Vendr.Deploy 2.0.1 via Nuget, I get the following error
`Unable to resolve dependency 'Lucene.Net.QueryParser'.`

I've tried on a couple of existing projects, I get the same error on all.

I also tried creating a new VS solution, installed Umbraco 8.17.2 via Nuget, then installed Vendr.Deploy 2.0.1, I got the same error here.

**Comment by mattbrailsford** [comment]
I think this might be the thing that I mentioned on the forum about beta dependencies. It's not really our dependency that's the problem, it's `Examine.Lucene` https://www.nuget.org/packages/Examine.Lucene/

This currently is a public release that has a beta dependency on `Lucene.Net.QueryParser` and `Lucene.Net.Replicator` which NuGet doesn't like. There is an interesting / long issue reported about this type of thing on the NuGet issue tracker https://github.com/NuGet/Home/issues/1365 and also one here https://github.com/NuGet/Home/issues/2944

I'm not entirely sure what the resolution is.

**Comment by MichaelNielsenDK** [comment]
Ok, I wasn't sure if it was related to Umbraco or not. I'll just close this again.

**Comment by MichaelNielsenDK** [comment]
Just to follow up, and completely understand the issue:

Why aren't we seeing this issue with all Umbraco projects then?

And what is the work-around, as I can't find any option to allow restoring prerelease dependencies in the Nuget Manager in VIsual Studio?

**Comment by mattbrailsford** [comment]
Good question, I'm not entirely sure to be honest.

From the looks of the NuGet issues above, it should be consistent across the board so is indeed weird that it doesn't have an issue on a basic install. What version of of that DLL gets installed during a normal Umbraco install?

**Comment by MichaelNielsenDK** [comment]
Which one Examine or Lucene.Net?

**Comment by mattbrailsford** [comment]
`Lucene.Net.QueryParser`

**Comment by MichaelNielsenDK** [comment]
Edit: I only see that assembly on v9 projects, not v8.

**Comment by mattbrailsford** [comment]
Hmm, it's very weird. Traversing through the dependency chain it flows as follows:

````
Vendr.Deploy
Vendr.Umbraco.Startup
UmbracoCms.Web
Examine
Examine.Lucene
Lucene.Net.QueryParser
````

So `Vendr.Deploy` just has a dependency on `Vendr.Umbraco.Startup` which has the `UmbracoCms.Web` dependency which has the `Examine` dependency so I really would expect a normal Umbraco v8 install to have that DLL. There is nothing in `Vendr.Deploy` that expressly requires it. It's all indirectly through the dependency chain 🤔

**Comment by MichaelNielsenDK** [comment]
Umbraco 8 dependency constraint for Examine is (>= 1.2.0 && < 1.999999.0). Everything below Examine 2.0 does not have a dependency to Examine.Lucene.

**Comment by mattbrailsford** [comment]
Ahhh, good point. I was just clicking through the dependency chain on NuGet.org

Hmm, I wonder if this is similar to this issue I had https://dev.to/mattbrailsford/fixing-analyzer-problems-in-multi-targeted-umbraco-packages-3ijk whereby, because my package is dual targeted, visual studio is making some weird assumptions and attempting to resolve the entire dependency chain, even for the version it doesn't need for a .NET Framework solution 🤔
