### ISSUE TITLE
Revisions changes via Umbraco Cloud

### ISSUE THREAD

**Issue by TQ-Benji** [vendrhub/vendr-deploy#22]
Noticed that we get alot of "Adding vendr-payment-method 'Opayo'" etc commits on our cloud repo after a deployment.

Two things keep coming up 

1. The amount of decimals in Prices array value property, locally it puts 1 dp cloud sets it to 3 dp

2.  We see that the order of properties inside the "PaymentProviderSettings" json section is changing but to no specific order its different every time. eg

local pushed structure
"PaymentProviderSettings": {
    "ErrorUrl": "/checkout/error",
    "IntegrationKey": "....",
    "ContinueUrl": "/checkout/confirmation",
    "VendorName": "sprucewoolltd",
    "IntegrationPassword": "...",
    "Three3dSecureRedirectUrl": "/checkout/3d-secure",
    "NotificationUrl": "https://#####/umbraco/surface/OpayoPI/Notify",
    "CancelUrl": "/checkout/cancel"
  },

Umbraco Cloud Commit changes it too
"PaymentProviderSettings": {
    "ContinueUrl": "/checkout/confirmation",
    "ErrorUrl": "/checkout/error",
    "NotificationUrl": "https://#####/umbraco/surface/OpayoPI/Notify",
    "VendorName": "sprucewoolltd",
    "IntegrationPassword": "...",
    "Three3dSecureRedirectUrl": "/checkout/3d-secure",
    "CancelUrl": "/checkout/cancel",
    "IntegrationKey": "..."
  },

**Comment by mattbrailsford** [comment]
Hmm, good spot. 

I could have sworn we resolved the decimal places issue as we definitely have something in place for this, but maybe it's not working as expected.

Regarding the settings order, maybe we need to look at enforcing a sort order on these alphabetically or something. I'll have to see what is possible.

**Comment by tormnator** [comment]
I think the settings order needs to be fixed. I'm seeing a never ending story of vendr-payment-method__***.uda files needing to be pulled from the Cloud Dev environment, and later needing to be pushed from the local environment. Here's screenshot of differences between the files in our case:

![image](https://user-images.githubusercontent.com/15617453/234654729-ba5625c6-4421-42e1-9bfe-5266afdc0a46.png)

**Comment by mattbrailsford** [comment]
Ok, so I've submitted an update that swaps the use of dictionaries for those values to a `SortedDictionary` which I believe should ensure the keys remain sorted during serialization. This should be on our unstable feed at https://nuget.outfield.digital/unstable/vendr/v3/index.json (v3.1.1-beta0002) if you want to give this a try and see if it resolves your issue

**Comment by TQ-Benji** [comment]
Thanks. That beta looks to of fixed the ordering of properties.

Still getting the number of decimal places issue.

**Comment by mattbrailsford** [comment]
Oops, forgot about that one. I think i've found that issue too now so if you want to try beta0003 and confirm this, that would be great

**Comment by TQ-Benji** [comment]
Sadly still does the changes, saving locally puts it to 1 dp and cloud set its to 3 dp after pushing

**Comment by mattbrailsford** [comment]
Shoot. Ok, well have have to try and setup a cloud environment to test this on then and see what it's not doing what it should. I'll get back to you when I can.

**Comment by mattbrailsford** [comment]
Could someone experiencing this issue share screenshots of the differing prices in the uda files on the different environments?

**Comment by TQ-Benji** [comment]
Hi Matt,

Here a image of the commit after a push that then changes the dp of the price for shipping methods and payment methods
![image](https://github.com/vendrhub/vendr-deploy/assets/60918405/f7f787b6-9161-4522-bf3d-fe6ab19f122f)

**Comment by mattbrailsford** [comment]
Excellent! Thank you. We've managed to replicate this and are looking at a fix in Umbraco Deploy 👍

**Comment by mattbrailsford** [comment]
Ok, so I've pushed out a 3.1.1 release of Vendr Deploy with various sorting fixes to ensure any inner entities in lists should get serialized in the same order every time preventing commits due to order changes.

Regarding rounding, this has been identified to be an Umbraco Deploy issue which is being resolved in https://github.com/umbraco/Umbraco-Deploy/pull/760 so I'll close this issue and any further discussions around rounding can occur there.
