### ISSUE TITLE
Vendr 1.5.0 - Product Attributes not transferred with content on Umbraco Cloud

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-deploy#4]
Not sure if this is a bug or feature request. 🤷‍♂️😊

Product Attributes are not transferred with content on Umbraco Cloud, which causes problems with variants on both frontend and backend. 

**Steps To Reproduce**
1. On your local installation, setup a Product Attribute, and create variants on a product with it
2. Transfer content to environment on Umbraco Cloud
3. Go into variant list and click on a variant, it will refresh the page to the Umbraco backend startpage. If you've set "Preserve log" on the console, you'll see the error below

```
TypeError: Cannot read property 'alias' of null
    at vendr.controllers.js?cdv=1730620494:736
    at Array.map (<anonymous>)
    at editBlock (vendr.controllers.js?cdv=1730620494:732)
    at VariantsAppController.vm.editVariantRow (vendr.controllers.js?cdv=1730620494:894)
    at ChildScope.itemClick (vendr.controllers.js?cdv=1730620494:554)
    at fn (eval at compile (angular.js?cdv=1730620494:16486), <anonymous>:4:370)
    at vendrTableController.destination.<computed> [as onClick] (angular.js?cdv=1730620494:11475)
    at vendrTableController.vm.clickItem (vendr.directives.js?cdv=1730620494:1548)
    at fn (eval at compile (angular.js?cdv=1730620494:16486), <anonymous>:4:388)
    at callback (angular.js?cdv=1730620494:29019)
```
Variants will also be missing in the frontend. 

Manually creating the product attributes will fix it. 

Umbraco v8.10.1
Vendr 1.5.0-rc0066
Vendr.Deploy 0.1.1

**Comment by mattbrailsford** [comment]
I've moved this issue to the Umbraco Deploy repo as I think this is going to need some kind of resolver for the variants prop editor. As the attributes are changeable this can't use the same approach as the settings, so we'll need to see what is possible with transferring custom data as part of deploy.

Thankfully, we based the attribute usage on attribute aliases so that these can be manually fixed by creating attributes with the same aliases, so it workaroundable to a degree.

**Comment by mattbrailsford** [comment]
So brief chat with Warren and he's pointed me in the direction of a few things to look into.

We will need a value connector for the variants prop editor (it's unclear in core if anything that uses the block editor data structure "should just work" or not, but I would guess not). Here is the connector for the block list editor https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/dev-v3/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs#L79

If what I understand is correct, then we will also need a ProductAttribute (Maybe presets?) service connector too and I'm guessing that by having a dependency from the value connector to the product attribute artifact, Umbraco should know to deploy the attribute too.

**Comment by mattbrailsford** [comment]
Closing this issue as there is now a PR #6 which aims to resolve this. Any further discussion can occur on the PR.
