### ISSUE TITLE
Data extraction on DEV environment on Umbraco Cloud fails

### ISSUE THREAD

**Issue by aguyfromdenmark** [vendrhub/vendr-deploy#8]
**Describe the bug**
When creating a new DEV environment for a site using Vendr, running on Umbraco Cloud, the data extraction will fail.

**Steps To Reproduce**
1. Have a site on Umbraco Cloud that has Vendr installed.
2. Create a new Development environment for the site
3. Wait for the environment to be done setting up, and for data extraction to complete.

**Expected behavior**
The extraction completes without errors.

**Additional context**
The site is running Umbraco 8.14.4 with deploy version 4.1.4. Vendr is setup with Vencr.Core.Web 1.8.6 and Vendr.PaymentProviders.Invoicing 1.1.0.

**Vendr version:**
Vendr version 1.8.6.

Full error from data extraction:
`{"Date":"2021-09-23T11:32:41.118347+00:00","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_vendrCountry_vendrStore\". The conflict occurred in database \"r2plbxn1x0w\", table \"dbo.vendrStore\", column 'id'.\r\nThe statement has been terminated.","Ex":{"Errors":[{"Source":".Net SqlClient Data Provider","Number":547,"State":0,"Class":16,"Server":"umbwesrv03.database.windows.net,1433","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_vendrCountry_vendrStore\". The conflict occurred in database \"r2plbxn1x0w\", table \"dbo.vendrStore\", column 'id'.","Procedure":"","LineNumber":1},{"Source":".Net SqlClient Data Provider","Number":3621,"State":0,"Class":0,"Server":"umbwesrv03.database.windows.net,1433","Message":"The statement has been terminated.","Procedure":"","LineNumber":1}],"ClientConnectionId":"868b3af0-b73a-41b9-b4a0-c84a90d74b10","ClassName":"System.Data.SqlClient.SqlException","Message":"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_vendrCountry_vendrStore\". The conflict occurred in database \"r2plbxn1x0w\", table \"dbo.vendrStore\", column 'id'.\r\nThe statement has been terminated.","Data":{"HelpLink.ProdName":"Microsoft SQL Server","HelpLink.ProdVer":"12.00.2195","HelpLink.EvtSrc":"MSSQLServer","HelpLink.EvtID":"547","HelpLink.BaseHelpUrl":"http://go.microsoft.com/fwlink","HelpLink.LinkId":"20476"},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 272\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\n   at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\n   at NPoco.Database.Save[T](T poco)\r\n   at Vendr.Core.Persistence.Repositories.CountryRepository.Save(CountryState state, CountryState originalState)\r\n   at Vendr.Core.Services.CountryService.SaveCountry(Country entity)\r\n   at Vendr.Core.Api.CoreVendrApi.SaveCountry(Country entity)\r\n   at Vendr.Deploy.Connectors.ServiceConnectors.VendrCountryServiceConnector.Pass2(ArtifactDeployState`2 state, IDeployContext context)\r\n   at Vendr.Deploy.Connectors.ServiceConnectors.VendrCountryServiceConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)\r\n   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)\r\n   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nOnError\nSystem.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Data.SqlClient.SqlConnection\nVoid OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])","HResult":-2146232060,"Source":".Net SqlClient Data Provider","WatsonBuckets":null},"Sender":"Umbraco.Deploy.Work.WorkItems.DiskReadWorkItem"}`

**Comment by mattbrailsford** [comment]
I'm going to close this issue for now as this has already been raised on the support forums https://our.umbraco.com/packages/website-utilities/vendr/vendr-support/107156-after-restoring-local-site-from-dev-then-getting-issue

As it is yet unclear if it's a bug, or a specific instance issue, I'll wait to see how the discussion goes on the forum. If it does end up being a bug, I'll re-open this issue accordingly.
